/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElError: typeof import('element-plus/es')['ElError']
  const ElSuccess: typeof import('element-plus/es')['ElSuccess']
  const ElWarning: typeof import('element-plus/es')['ElWarning']
}
